apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-mesh-ui
spec:
  selector:
    matchLabels:
      run: service-mesh-ui
  replicas: 2
  template:
    metadata:
      labels:
        run: service-mesh-ui
    spec:
      containers:
      - name: service-mesh-ui
        image: docker.io/<replace_with_dockerhub_account>/service-mesh-ui:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: service-mesh-ui-service
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    run: service-mesh-ui
  type: LoadBalancer
status:
  loadBalancer: {}
