apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-app
spec:
  selector:
    matchLabels:
      run: payment-app
  replicas: 2
  template:
    metadata:
      labels:
        run: payment-app
    spec:
      containers:
      - name: payment-app
        image: docker.io/dfoley3118/payment-app:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: payment-app
  type: LoadBalancer
status:
  loadBalancer: {}
