apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-app
spec:
  selector:
    matchLabels:
      run: inventory-app
  replicas: 2
  template:
    metadata:
      labels:
        run: inventory-app
    spec:
      containers:
      - name: inventory-app
        image: docker.io/<replace_with_dockerhub_account>/inventory-app:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: inventory-app
  type: LoadBalancer
status:
  loadBalancer: {}
